# Generated by Django 3.2.4 on 2022-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Telefono', models.IntegerField(blank=True, null=True)),
                ('CantidadDeEnviosRealizados', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('PrecioDeCompra', models.IntegerField(blank=True, default=0, null=True)),
                ('PrecioDeVenta', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
