# Generated by Django 3.2.4 on 2022-03-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mula',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='objeto',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
