# Generated by Django 3.2.4 on 2022-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador', '0005_article_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto_Extra',
            fields=[
                ('token', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Cantidad_de_dinero', models.FloatField(blank=True, default=0, null=True)),
                ('notas', models.TextField(blank=True, max_length=99999, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='objeto',
            name='PrecioDeCompra',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='PrecioDeVenta',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('token', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Hay_que_pagar_ida_y_vuelta', models.BooleanField(default=True)),
                ('Gasto_total_en_pasajes', models.FloatField(blank=True, default=0, null=True)),
                ('Dinero_Total_obtenido', models.FloatField(blank=True, default=0, null=True)),
                ('Ganancia', models.FloatField(blank=True, default=0, null=True)),
                ('Gastos_extras', models.ManyToManyField(to='Controlador.Gasto_Extra')),
                ('Inventario', models.ManyToManyField(to='Controlador.Objeto')),
            ],
        ),
    ]
