# Generated by Django 3.2.4 on 2022-03-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador', '0006_auto_20220314_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
