# Generated by Django 3.2.4 on 2022-03-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador', '0008_envio_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('token', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('Cantidad_de_ejemplares', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Controlador.objeto')),
            ],
        ),
        migrations.AlterField(
            model_name='envio',
            name='Inventario',
            field=models.ManyToManyField(to='Controlador.Pack'),
        ),
    ]
