# Generated by Django 3.2.4 on 2022-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador', '0009_auto_20220316_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('token', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('packs', models.ManyToManyField(to='Controlador.Pack')),
            ],
        ),
        migrations.AlterField(
            model_name='envio',
            name='Inventario',
            field=models.ManyToManyField(to='Controlador.Inventario'),
        ),
    ]
