# Generated by Django 3.2.4 on 2022-06-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador', '0010_auto_20220613_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='Inventario',
        ),
        migrations.AddField(
            model_name='envio',
            name='Inventario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Controlador.inventario'),
            preserve_default=False,
        ),
    ]
