# Generated by Django 3.2.4 on 2022-06-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador', '0012_auto_20220613_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='Hay_que_pagar_ida_y_vuelta',
        ),
        migrations.AddField(
            model_name='envio',
            name='Dinero_Total_Invertido',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
